### ISSUE TITLE
Cyrillic support

### ISSUE THREAD

**Issue by kshmelkov** [ardagnir/pterosaur#33] opened 2015-02-27 21:06 UTC
There is a problem with cyrillic input. When I type in Russian, I get latin capital letters and digits (it seems like somewhere there is a module division of charcode). Obviously, in vim and in firefox without pterosaur it is fine. In english pterosaur works perfectly, great plugin.

My config: ArchLinux, Firefox 36.
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Feb  4 2015 08:02:36)
A fragment from .vimrc
set encoding=utf-8
set fileencoding=utf-8

**Comment by ardagnir** [comment] 2015-03-05 18:14
This is a duplicate of #29

**Closed** 2015-03-05 18:14 UTC
Labels: duplicate
